---
title: "chrysie's drain dump"
author: "chrysie"
date: "2024-06-04"
output: html_document
---

```{r}
our_data <- read.csv("../data/our_data.csv")

```


# recoding the variables so they're numeric
```{r ks2}
unique(our_data$KS2EnglishtestNUM)
{
# [1] "4"                                                                        
# [2] NA                                                                         
# [3] "3"                                                                        
# [4] "5"                                                                        
# [5] "2"                                                                        
# [6] "Level 1, N (below level 2 in test) or B (working below level of the test)"
# [7] "6"
}
unique(our_data$KS2MathstestNUM)
{
# [1] "4"                                                               
# [2] NA                                                                
# [3] "5"                                                               
# [4] "3"                                                               
# [5] "2"                                                               
# [6] "6"                                                               
# [7] "N (below level 2 in test) or B (working below level of the test)"
}

# change only the text entries of each variable to be '1' and then ensure it's all read as numeric
library(dplyr)

our_data <- our_data %>%
  mutate(KS2EnglishtestNUM = case_when(
    KS2EnglishtestNUM == "Level 1, N (below level 2 in test) or B (working below level of the test)" ~ "1",
    TRUE ~ KS2EnglishtestNUM  # this line ensures that all other values remain unchanged
  ))

# checking
unique(our_data$KS2EnglishtestNUM)  #"4" NA  "3" "5" "2" "1" "6"
our_data$KS2EnglishtestNUM <- as.factor(our_data$KS2EnglishtestNUM)

our_data <- our_data %>%
  mutate(KS2MathstestNUM = case_when(
    KS2MathstestNUM == "N (below level 2 in test) or B (working below level of the test)" ~ "1",
    TRUE ~ KS2MathstestNUM  # this line ensures that all other values remain unchanged
  ))

# checking
unique(our_data$KS2MathstestNUM)  #"4" NA  "5" "3" "2" "6" "1"
our_data$KS2MathstestNUM <- as.factor(our_data$KS2MathstestNUM)
```


```{r ks3}
unique(our_data$Y7EnglishNC)
{
#[1] "6b" NA   "5b" "5c" "4a" "5a" "6c" "7b" "6a" "4b" "4c" "3b" "2a" "3c" "2b" "3a" "2c"
#[18] "7c"
}
unique(our_data$Y7MathsNC)
{
#[1] "6b" NA   "6c" "5c" "4a" "4c" "5a" "6a" "5b" "4b" "3a" "2a" "2b" "3b" "3c" "7b" "7a"
#[18] "8b" "7c" "8c" "2c"
}

# collapse across sublevels of a level i.e., a, b, c so that there's only level 2, 3, 4, 5, etc
our_data <- our_data %>%
  mutate(Y7EnglishNC = case_when(
    Y7EnglishNC %in% c("2a", "2b", "2c") ~ "2",
    Y7EnglishNC %in% c("3a", "3b", "3c") ~ "3",
    Y7EnglishNC %in% c("4a", "4b", "4c") ~ "4",
    Y7EnglishNC %in% c("5a", "5b", "5c") ~ "5",
    Y7EnglishNC %in% c("6a", "6b", "6c") ~ "6",
    Y7EnglishNC %in% c("7a", "7b", "7c") ~ "7",
    TRUE ~ Y7EnglishNC  # this line ensures that all other values remain unchanged
  ))

# checking
unique(our_data$Y7EnglishNC)  #"6" NA  "5" "4" "7" "3" "2"
our_data$Y7EnglishNC <- as.factor(our_data$Y7EnglishNC)

our_data <- our_data %>%
  mutate(Y7MathsNC = case_when(
    Y7MathsNC %in% c("2a", "2b", "2c") ~ "2",
    Y7MathsNC %in% c("3a", "3b", "3c") ~ "3",
    Y7MathsNC %in% c("4a", "4b", "4c") ~ "4",
    Y7MathsNC %in% c("5a", "5b", "5c") ~ "5",
    Y7MathsNC %in% c("6a", "6b", "6c") ~ "6",
    Y7MathsNC %in% c("7a", "7b", "7c") ~ "7",
    Y7MathsNC %in% c("8a", "8b", "8c") ~ "8",
    TRUE ~ Y7MathsNC  # this line ensures that all other values remain unchanged
  ))

# checking
unique(our_data$Y7MathsNC)  #"6" NA  "5" "4" "3" "2" "7" "8"
our_data$Y7MathsNC <- as.factor(our_data$Y7MathsNC)
```


```{r tidy up}
our_data <- our_data %>%
  rename(KS2Eng = KS2EnglishtestNUM, KS2Mat = KS2MathstestNUM, KS3Eng = Y7EnglishNC, KS3Mat = Y7MathsNC)



```

