Authors: Tat and Chrysie
Date: 30/4/2024
Purpose: crying
Version: 1
Notes: it worked when andrea pointed out the obvious

# loading the script
``` {r}
#install.packages("foreign")
library(foreign)
#OR
install.packages("haven")
library(haven)

st_data <- foreign::read.spss('../data/SchoolTransitionData.sav', to.data.frame = T)

# saving the spss dataframe as a csv because excel supremacy
output_path <- "../data/st_data.csv"  
write.csv(st_data, file = output_path, row.names = TRUE)

```

# getting our data separate from the og data
``` {r}
# loading the data into my environment
st_data <- read.csv("../data/st_data.csv")

# variable column codes
{
# "X" = ppt number
# "ID" = ppt ID
# 
# #### [**SDQ**]{.underline} 
# 
# -   Child Wave 1: C1_B1 to 25 - recode: 7, 11, 14, 21, 25
# -   Child Wave 2: C2_B1 to 25 - recode: 7, 11, 14, 21, 25
# -   Child Wave 3: C3_B1 to 25 - recode: 7, 11, 14, 21, 25
#   
#   # Not True = 0
#   # Sort of True = 1
#   # Certainly True = 2
# 
# #### [**SDQ Impacts**]{.underline}
# 
# -   cut because data is only from parents and teachers, not the children
#     themselves
# 
# #### [**Wentzel's**]{.underline}
# 
# -   Child Wave 1: C1_AG1 to 4
# -   Child Wave 2: C2_AG1 to 4
# -   Child Wave 3: C3_AG1 to 4
#     
#     #Never = 1, Seldom = 2, Sometimes = 3, Often = 4, Always = 5, none to recode
# 
# #### [**FSM**]{.underline}
# 
# -   "FSM" #0 for no, 1 for yes
# 
# #### [**SCQ: School Concerns Questionnaire**]{.underline}
#
# -   Child Wave 1: C1_SConcern1 to 20
# -   Child Wave 2: C2_SConcern1 to 20
# -   Child Wave 3: C3_SConcern1 to 20
#     # just add 1 and 10 bc the others are numbers
# 
# #### [**CDPQ: Child Development Project Questionnaire (school liking)**]{.underline}
# 
# -   Child Wave 1: N/A
# -   Child Wave 2: C2_SL1 to 5 - recode 1, 4
# -   Child Wave 3: C3_SL1 to 5 - recode 3, 5
# #delete because no wave 1
#     
#     
# #### [**CDPQ: Child Development Project Questionnaire (trust and respect for teachers)**]{.underline}
# 
# -   Child Wave 1: C1_LT1 to 10 - recode: 1,3,5,7,9,10
# -   Child Wave 2: C2_LT1 to 10 - recode: 1,3,5,7,9,10
# -   Child Wave 3: C3_LT1 to 10 - recode: 2,4,6,8
#     
#     #YES!! = 1, yes = 2, no = 3, NO!! = 4
# 
# #### [**LiCs: School-oriented version fo the Loneliness in Children scale**]{.underline}
# 
# -   Child Wave 1: C1_L1 to 16 - recode: 1,3,5,7,10,15
# -   Child Wave 2: C1_L1,2,6,7,11,14,15 - recode: 1,7,15
# -   Child Wave 3: C1_L1,2,6,7,11,14,15 - recode: 1,7,15
#     
#     #not true at all = 1, hardly ever true = 2, sometimes true = 3, true most of the time = 4, always true = 5
# 
# #### [**KS2: English, Maths, Science**]{.underline}
# -   "KS2MathstestNUM" - THIS
# -   "KS2EnglishtestNUM" - THIS
# -   "KS2EnglishTANUM"
# -   "KS2EngComb"
# 
# #### [**KS3: English, Maths, Science**]{.underline} 
# -   "Y7EnglishNC" - THIS
# -   "Y7MathsNC" - THIS
# -   "Y7ScienceNC"
# -   "Y7NC"
# -   "Y7EnglishIMYC" 
# -   "Y7MathsIMYC" 
# -   "Y7ScienceIMYC"
# -   "Y7IMYC"
# -   "Eng7"
# -   "Math7"
# -   "Sci7" # no science
}

# NOTE: english and maths are all numbers whatever the numbers mean

# getting all the columns for each measure
cols_sdq <- grep("^C[123]_B[1-25]", names(st_data), value = TRUE)
cols_wen <- grep("^C[123]_AG[1-4]$", names(st_data), value = TRUE)
cols_sqc <- grep("^C[123]_SConcern([1-9]|1[0-9]|20)$", names(st_data), value = TRUE)
cols_lt <- grep("^C[123]_LT[1-9]|^C[123]_LT10$", names(st_data), value = TRUE)
cols_lon <- grep("^C[123]_L([1-9]|1[0-5]|15)$", names(st_data), value = TRUE)
cols_ks2 <- c("KS2MathstestNUM", "KS2EnglishtestNUM")
cols_ks3 <- c("Y7EnglishNC", "Y7MathsNC")

# making our df using the chosen variable columns
library(dplyr)

our_data <- st_data %>%
  select("X", "ID", cols_sdq, cols_wen, "FSM", cols_sqc, cols_lt, cols_lon, cols_ks2, cols_ks3)

write.csv(our_data, file = "../data/our_data.csv", row.names = FALSE)

```

# recoding the data to have numeric values
```{r SDQ}
# SDQ

our_data <- our_data %>% 
  mutate(
    C1_B1 = factor(C1_B1, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B2 = factor(C1_B2, levels = c("Not true", "Sort of true", "Certainly true")), 
    C1_B5 = factor(C1_B5, levels = c("Not true", "Sort of true", "Certainly true")), 
    C1_B10 = factor(C1_B10, levels = c("Not true", "Sort of true", "Certainly true")), 
    C1_B11 = factor(C1_B11, levels = c("Certainly true", "Sort of true", "Not true")),
    C1_B12 = factor(C1_B12, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B13 = factor(C1_B13, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B14 = factor(C1_B14, levels = c("Certainly true", "Sort of true", "Not true")),
    C1_B15 = factor(C1_B15, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B16 = factor(C1_B16, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B17 = factor(C1_B17, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B18 = factor(C1_B18, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B19 = factor(C1_B19, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B20 = factor(C1_B20, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B21 = factor(C1_B21, levels = c("Certainly true", "Sort of true", "Not true")),
    C1_B22 = factor(C1_B22, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B23 = factor(C1_B23, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B24 = factor(C1_B24, levels = c("Not true", "Sort of true", "Certainly true")),
    C1_B25 = factor(C1_B25, levels = c("Certainly true", "Sort of true", "Not true"))
  )

##2
our_data <- our_data %>% 
  mutate(
    C2_B1 = factor(C2_B1, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B2 = factor(C2_B2, levels = c("Not true", "Sort of true", "Certainly true")), 
    C2_B5 = factor(C2_B5, levels = c("Not true", "Sort of true", "Certainly true")), 
    C2_B10 = factor(C2_B10, levels = c("Not true", "Sort of true", "Certainly true")), 
    C2_B11 = factor(C2_B11, levels = c("Certainly true", "Sort of true", "Not true")),
    C2_B12 = factor(C2_B12, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B13 = factor(C2_B13, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B14 = factor(C2_B14, levels = c("Certainly true", "Sort of true", "Not true")),
    C2_B15 = factor(C2_B15, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B16 = factor(C2_B16, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B17 = factor(C2_B17, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B18 = factor(C2_B18, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B19 = factor(C2_B19, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B20 = factor(C2_B20, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B21 = factor(C2_B21, levels = c("Certainly true", "Sort of true", "Not true")),
    C2_B22 = factor(C2_B22, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B23 = factor(C2_B23, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B24 = factor(C2_B24, levels = c("Not true", "Sort of true", "Certainly true")),
    C2_B25 = factor(C2_B25, levels = c("Certainly true", "Sort of true", "Not true"))
  )

##3
our_data <- our_data %>% 
  mutate(
    C3_B1 = factor(C3_B1, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B2 = factor(C3_B2, levels = c("Not true", "Sort of true", "Certainly true")), 
    C3_B5 = factor(C3_B5, levels = c("Not true", "Sort of true", "Certainly true")), 
    C3_B10 = factor(C3_B10, levels = c("Not true", "Sort of true", "Certainly true")), 
    C3_B11 = factor(C3_B11, levels = c("Certainly true", "Sort of true", "Not true")),
    C3_B12 = factor(C3_B12, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B13 = factor(C3_B13, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B14 = factor(C3_B14, levels = c("Certainly true", "Sort of true", "Not true")),
    C3_B15 = factor(C3_B15, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B16 = factor(C3_B16, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B17 = factor(C3_B17, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B18 = factor(C3_B18, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B19 = factor(C3_B19, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B20 = factor(C3_B20, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B21 = factor(C3_B21, levels = c("Certainly true", "Sort of true", "Not true")),
    C3_B22 = factor(C3_B22, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B23 = factor(C3_B23, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B24 = factor(C3_B24, levels = c("Not true", "Sort of true", "Certainly true")),
    C3_B25 = factor(C3_B25, levels = c("Certainly true", "Sort of true", "Not true"))
  )

```

```{r Wentzel's}
# Wentzel's
# Never = 1, Seldom = 2, Sometimes = 3, Often = 4, Always = 5, none to recode

library(dplyr)

label_levels <- c("Never", "Seldom", "Sometimes", "Often", "Always")

our_data <- our_data %>%
  mutate(across(c(C1_AG1, C1_AG2, C1_AG3, C1_AG4,
                  C2_AG1, C2_AG2, C2_AG3, C2_AG4,
                  C3_AG1, C3_AG2, C3_AG3, C3_AG4),
                ~ factor(.x, levels = c(1, 2, 3, 4, 5), labels = label_levels)))

```

```{r FSM}
#### [**FSM**]{.underline}

## "FSM" #0 for no, 1 for yes

our_data <- our_data %>% 
  mutate(
    FSM = factor(FSM, levels = c(0, 1), labels = c("No", "Yes")))

```

``` {r SCQ}
#### [**SCQ: School Concerns Questionnaire**]{.underline}

# Child Wave 1: C1_SConcern1 to 20
# Child Wave 2: C2_SConcern1 to 20
# Child Wave 3: C3_SConcern1 to 20
    # just add 1 and 10 bc the others are numbers - Not at all worried, I get extremely worried about it

our_data <- our_data %>%
  mutate(
    C1_SConcern1 = factor(C1_SConcern1, levels = c("Not at all worried", "2", "3", "4", "5", "6", "7", "8", "9", "I get extremely worried about it"), 
          labels = c(1, 2, 3,4,5,6,7,8,9,10)),
C1_SConcern2 = factor(C1_SConcern2, levels = c("Not at all worried", "2", "3", "4", "5", "6", "7", "8", "9", "I get extremely worried about it"), 
          labels = c(1, 2, 3,4,5,6,7,8,9,10)),
C1_SConcern3 = factor(C1_SConcern3, levels = c("Not at all worried", "2", "3", "4", "5", "6", "7", "8", "9", "I get extremely worried about it") ,
          labels = c(1, 2, 3,4,5,6,7,8,9,10)))

# learning loops
levels_vec <- c("Not at all worried", "2", "3", "4", "5", "6", "7", "8", "9", "I get extremely worried about it")
labels_vec <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

columns_to_mutate <- c("C1_SConcern1", "C1_SConcern2", "C1_SConcern3", "C1_SConcern4", "C1_SConcern5", "C1_SConcern6", "C1_SConcern7", "C1_SConcern8", "C1_SConcern9", "C1_SConcern10", "C1_SConcern11", "C1_SConcern12", "C1_SConcern13", "C1_SConcern14", "C1_SConcern15", "C1_SConcern16", "C1_SConcern17", "C1_SConcern18", "C1_SConcern19", "C1_SConcern20", "C2_SConcern1", "C2_SConcern2", "C2_SConcern3", "C2_SConcern4", "C2_SConcern5", "C2_SConcern6", "C2_SConcern7", "C2_SConcern8", "C2_SConcern9", "C2_SConcern10", "C2_SConcern11", "C2_SConcern12", "C2_SConcern13", "C2_SConcern14", "C2_SConcern15", "C2_SConcern16", "C2_SConcern17", "C2_SConcern18", "C2_SConcern19", "C2_SConcern20", "C3_SConcern1", "C3_SConcern2", "C3_SConcern3", "C3_SConcern4", "C3_SConcern5", "C3_SConcern6", "C3_SConcern7", "C3_SConcern8", "C3_SConcern9", "C3_SConcern10", "C3_SConcern11", "C3_SConcern12", "C3_SConcern13", "C3_SConcern14", "C3_SConcern15", "C3_SConcern16", "C3_SConcern17", "C3_SConcern18", "C3_SConcern19", "C3_SConcern20")

our_data <- our_data %>%
  mutate_at(vars(columns_to_mutate), ~factor(., levels = levels_vec, labels = labels_vec))


```

```{r liking teachers}
# #### [**CDPQ: Child Development Project Questionnaire (trust and respect for teachers)**]{.underline}

# Child Wave 1: C1_LT1 to 10 - recode: 1,3,5,7,9,10
# Child Wave 2: C2_LT1 to 10 - recode: 1,3,5,7,9,10
# Child Wave 3: C3_LT1 to 10 - recode: 2,4,6,8
#     
#     #YES!! = 1, yes = 2, no = 3, NO!! = 4

levels_vec <- c("YES!!", "yes", "no", "NO!!")
labels_vec <- c(4, 3, 2, 1)

columns_to_mutate <- c("C1_LT1", "C1_LT3", "C1_LT5", "C1_LT7", "C1_LT9", "C1_LT10", "C2_LT1", "C2_LT3", "C2_LT5", "C2_LT7", "C2_LT9", "C2_LT10", "C3_LT2", "C3_LT4", "C3_LT6", "C3_LT8")

our_data <- our_data %>%
  mutate_at(vars(columns_to_mutate), ~factor(., levels = levels_vec, labels = labels_vec))

## recoding 
levels_vec <- c("YES!!", "yes", "no", "NO!!")
labels_vec <- c(1, 2, 3, 4)

columns_to_mutate <- c("C1_LT2", "C1_LT4", "C1_LT6", "C1_LT8", "C2_LT2", "C2_LT4", "C2_LT6", "C2_LT8", "C3_LT1", "C3_LT3", "C3_LT5", "C3_LT7", "C3_LT9", "C3_LT10")

our_data <- our_data %>%
  mutate_at(vars(columns_to_mutate), ~factor(., levels = levels_vec, labels = labels_vec)) 

```

```{r lonliness}
# [**LiCs: School-oriented version fo the Loneliness in Children scale**]{.underline}
# 
# Child Wave 1: C1_L1 to 15 - recode: 1,3,5,7,10,15
# Child Wave 2: C2_L1,2,6,7,11,14,15 - recode: 1,7,15
# Child Wave 3: C3_L1,2,6,7,11,14,15 - recode: 1,7,15
#     
## not true at all = 1, hardly ever true = 2, sometimes true = 3, true most of the time = 4, always true = 5

levels_vec <- c("Not true at all", "Hardly ever true", "Sometimes true", "True most of the time", "Always true")
labels_vec <- c(1, 2, 3, 4, 5)

columns_to_mutate <- c("C1_L2","C1_L4","C1_L6","C1_L8","C1_L9","C1_L11","C1_L12","C1_L13","C1_L14", "C2_L2", "C2_L6", "C2_L11", "C2_L14", "C3_L2", "C3_L6", "C3_L11", "C3_L14")

our_data <- our_data %>%
  mutate_at(vars(columns_to_mutate), ~factor(., levels = levels_vec, labels = labels_vec))

#recoding
levels_vec <- c("Not true at all", "Hardly ever true", "Sometimes true", "True most of the time", "Always true")
labels_vec <- c(5, 4, 3, 2, 1)

columns_to_mutate <- c("C1_L1", "C1_L3","C1_L5","C1_L7","C1_L10","C1_L15", "C2_L1", "C2_L7", "C2_L15", "C3_L1", "C3_L7", "C3_L15")

our_data <- our_data %>%
  mutate_at(vars(columns_to_mutate), ~factor(., levels = levels_vec, labels = labels_vec)) 
```

```{r ks2}
unique(our_data$KS2EnglishtestNUM)
{
# [1] "4"                                                                        
# [2] NA                                                                         
# [3] "3"                                                                        
# [4] "5"                                                                        
# [5] "2"                                                                        
# [6] "Level 1, N (below level 2 in test) or B (working below level of the test)"
# [7] "6"
}
unique(our_data$KS2MathstestNUM)
{
# [1] "4"                                                               
# [2] NA                                                                
# [3] "5"                                                               
# [4] "3"                                                               
# [5] "2"                                                               
# [6] "6"                                                               
# [7] "N (below level 2 in test) or B (working below level of the test)"
}

# change only the text entries of each variable to be '1' and then ensure it's all read as numeric
library(dplyr)

our_data <- our_data %>%
  mutate(KS2EnglishtestNUM = case_when(
    KS2EnglishtestNUM == "Level 1, N (below level 2 in test) or B (working below level of the test)" ~ "1",
    TRUE ~ KS2EnglishtestNUM  # this line ensures that all other values remain unchanged
  ))

# checking
unique(our_data$KS2EnglishtestNUM)  #"4" NA  "3" "5" "2" "1" "6"
our_data$KS2EnglishtestNUM <- as.factor(our_data$KS2EnglishtestNUM)

our_data <- our_data %>%
  mutate(KS2MathstestNUM = case_when(
    KS2MathstestNUM == "N (below level 2 in test) or B (working below level of the test)" ~ "1",
    TRUE ~ KS2MathstestNUM  # this line ensures that all other values remain unchanged
  ))

# checking
unique(our_data$KS2MathstestNUM)  #"4" NA  "5" "3" "2" "6" "1"
our_data$KS2MathstestNUM <- as.factor(our_data$KS2MathstestNUM)
```

```{r ks3}
unique(our_data$Y7EnglishNC)
{
#[1] "6b" NA   "5b" "5c" "4a" "5a" "6c" "7b" "6a" "4b" "4c" "3b" "2a" "3c" "2b" "3a" "2c"
#[18] "7c"
}
unique(our_data$Y7MathsNC)
{
#[1] "6b" NA   "6c" "5c" "4a" "4c" "5a" "6a" "5b" "4b" "3a" "2a" "2b" "3b" "3c" "7b" "7a"
#[18] "8b" "7c" "8c" "2c"
}

# collapse across sublevels of a level i.e., a, b, c so that there's only level 2, 3, 4, 5, etc
our_data <- our_data %>%
  mutate(Y7EnglishNC = case_when(
    Y7EnglishNC %in% c("2a", "2b", "2c") ~ "2",
    Y7EnglishNC %in% c("3a", "3b", "3c") ~ "3",
    Y7EnglishNC %in% c("4a", "4b", "4c") ~ "4",
    Y7EnglishNC %in% c("5a", "5b", "5c") ~ "5",
    Y7EnglishNC %in% c("6a", "6b", "6c") ~ "6",
    Y7EnglishNC %in% c("7a", "7b", "7c") ~ "7",
    TRUE ~ Y7EnglishNC  # this line ensures that all other values remain unchanged
  ))

# checking
unique(our_data$Y7EnglishNC)  #"6" NA  "5" "4" "7" "3" "2"
our_data$Y7EnglishNC <- as.factor(our_data$Y7EnglishNC)

our_data <- our_data %>%
  mutate(Y7MathsNC = case_when(
    Y7MathsNC %in% c("2a", "2b", "2c") ~ "2",
    Y7MathsNC %in% c("3a", "3b", "3c") ~ "3",
    Y7MathsNC %in% c("4a", "4b", "4c") ~ "4",
    Y7MathsNC %in% c("5a", "5b", "5c") ~ "5",
    Y7MathsNC %in% c("6a", "6b", "6c") ~ "6",
    Y7MathsNC %in% c("7a", "7b", "7c") ~ "7",
    Y7MathsNC %in% c("8a", "8b", "8c") ~ "8",
    TRUE ~ Y7MathsNC  # this line ensures that all other values remain unchanged
  ))

# checking
unique(our_data$Y7MathsNC)  #"6" NA  "5" "4" "3" "2" "7" "8"
our_data$Y7MathsNC <- as.factor(our_data$Y7MathsNC)
```


```{r tidy up}
our_data <- our_data %>%
  rename(KS2Eng = KS2EnglishtestNUM, KS2Mat = KS2MathstestNUM, KS3Eng = Y7EnglishNC, KS3Mat = Y7MathsNC)

```

