---
title: "zoe's brain dump"
author: "zoe"
date: "2024-06-04"
output: html_document
---

```{r}

our_data <- read.csv("../data/our_data.csv")
library(dplyr)


#### [**SCQ: School Concerns Questionnaire**]{.underline}

# Child Wave 1: C1_SConcern1 to 20

# Child Wave 2: C2_SConcern1 to 20

# Child Wave 3: C3_SConcern1 to 20
    # just add 1 and 10 bc the others are numbers - Not at all worried, I get extremely worried about it

our_data <- our_data %>%
  mutate(
    C1_SConcern1 = factor(C1_SConcern1, levels = c("Not at all worried", "2", "3", "4", "5", "6", "7", "8", "9", "I get extremely worried about it"), 
          labels = c(1, 2, 3,4,5,6,7,8,9,10)),
C1_SConcern2 = factor(C1_SConcern2, levels = c("Not at all worried", "2", "3", "4", "5", "6", "7", "8", "9", "I get extremely worried about it"), 
          labels = c(1, 2, 3,4,5,6,7,8,9,10)),
C1_SConcern3 = factor(C1_SConcern3, levels = c("Not at all worried", "2", "3", "4", "5", "6", "7", "8", "9", "I get extremely worried about it") ,
          labels = c(1, 2, 3,4,5,6,7,8,9,10)))

# learning loops
levels_vec <- c("Not at all worried", "2", "3", "4", "5", "6", "7", "8", "9", "I get extremely worried about it")
labels_vec <- c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

columns_to_mutate <- c("C1_SConcern1", "C1_SConcern2", "C1_SConcern3", "C1_SConcern4", "C1_SConcern5", "C1_SConcern6", "C1_SConcern7", "C1_SConcern8", "C1_SConcern9", "C1_SConcern10", "C1_SConcern11", "C1_SConcern12", "C1_SConcern13", "C1_SConcern14", "C1_SConcern15", "C1_SConcern16", "C1_SConcern17", "C1_SConcern18", "C1_SConcern19", "C1_SConcern20", "C2_SConcern1", "C2_SConcern2", "C2_SConcern3", "C2_SConcern4", "C2_SConcern5", "C2_SConcern6", "C2_SConcern7", "C2_SConcern8", "C2_SConcern9", "C2_SConcern10", "C2_SConcern11", "C2_SConcern12", "C2_SConcern13", "C2_SConcern14", "C2_SConcern15", "C2_SConcern16", "C2_SConcern17", "C2_SConcern18", "C2_SConcern19", "C2_SConcern20", "C3_SConcern1", "C3_SConcern2", "C3_SConcern3", "C3_SConcern4", "C3_SConcern5", "C3_SConcern6", "C3_SConcern7", "C3_SConcern8", "C3_SConcern9", "C3_SConcern10", "C3_SConcern11", "C3_SConcern12", "C3_SConcern13", "C3_SConcern14", "C3_SConcern15", "C3_SConcern16", "C3_SConcern17", "C3_SConcern18", "C3_SConcern19", "C3_SConcern20")

our_data <- our_data %>%
  mutate_at(vars(columns_to_mutate), ~factor(., levels = levels_vec, labels = labels_vec))

```

``` {r}
# #### [**CDPQ: Child Development Project Questionnaire (trust and respect for teachers)**]{.underline}
# 
# -   Child Wave 1: C1_LT1 to 10 - recode: 1,3,5,7,9,10
# -   Child Wave 2: C2_LT1 to 10 - recode: 1,3,5,7,9,10
# -   Child Wave 3: C3_LT1 to 10 - recode: 2,4,6,8
#     
#     #YES!! = 1, yes = 2, no = 3, NO!! = 4

levels_vec <- c("YES!!", "yes", "no", "NO!!")
labels_vec <- c(1, 2, 3, 4)

columns_to_mutate <- c("C2_SL1", "C2_SL2", "C2_SL3", "C2_SL4", "C2_SL5", "C3_SL1", "C3_SL2", "C3_SL3", "C3_SL4", "C3_SL5", "C1_LT1", "C1_LT2", "C1_LT3", "C1_LT4", "C1_LT5", "C1_LT6", "C1_LT7", "C1_LT8", "C1_LT9", "C1_LT10", "C2_LT1", "C2_LT2", "C2_LT3", "C2_LT4", "C2_LT5", "C2_LT6", "C2_LT7", "C2_LT8", "C2_LT9", "C2_LT10", "C3_LT1", "C3_LT2", "C3_LT3", "C3_LT4", "C3_LT5", "C3_LT6", "C3_LT7", "C3_LT8", "C3_LT9", "C3_LT10")

our_data <- our_data %>%
  mutate_at(vars(columns_to_mutate), ~factor(., levels = levels_vec, labels = labels_vec))

## recoding 
levels_vec <- c("YES!!", "yes", "no", "NO!!")
labels_vec <- c(1, 2, 3, 4)

columns_to_mutate <- c("C2_SL1", "C2_SL2", "C2_SL3", "C2_SL4", "C2_SL5", "C3_SL1", "C3_SL2", "C3_SL3", "C3_SL4", "C3_SL5", "C1_LT1", "C1_LT2", "C1_LT3", "C1_LT4", "C1_LT5", "C1_LT6", "C1_LT7", "C1_LT8", "C1_LT9", "C1_LT10", "C2_LT1", "C2_LT2", "C2_LT3", "C2_LT4", "C2_LT5", "C2_LT6", "C2_LT7", "C2_LT8", "C2_LT9", "C2_LT10", "C3_LT1", "C3_LT2", "C3_LT3", "C3_LT4", "C3_LT5", "C3_LT6", "C3_LT7", "C3_LT8", "C3_LT9", "C3_LT10")

our_data <- our_data %>%
  mutate_at(vars(columns_to_mutate), ~factor(., levels = levels_vec, labels = labels_vec))

```